### ISSUE TITLE
Configuration with Windows and spaces in profile

### ISSUE THREAD

**Issue by JohnWallerStudioLabs** [deadem/notepad-pp-linter#1]
linter.xml example I'm trying to get working

```
<?xml version="1.0" encoding="utf-8" ?>
<NotepadPlus>
	<linter extension=".js" command="C:\Users\Firstname Lastname\AppData\Roaming\npm\eslint.cmd --format checkstyle"/> 
</NotepadPlus>
```

I run the following from the command line as specified by the configuration (.xml file) as the real time check .. and it works.

```
c:\"C:\Users\Firstname Lastname\AppData\Roaming\npm\eslint.cmd" --format checkstyle
eslint [options] file.js [file.js] [dir]

Basic configuration:
  --no-eslintrc                  Disable use of configuration from .eslintrc.*
  -c, --config path::String      Use this configuration, overriding .eslintrc.* config options if present
  --env [String]                 Specify environments
  --ext [String]                 Specify JavaScript file extensions - default: .js
  --global [String]              Define global variables
  --parser String                Specify the parser to be used
  --parser-options Object        Specify parser options

.....
```
The ["] are used to escape the [/s] between the firstname and lastname. Windows (non-network/domain users) don't contend with straight up usernames w/ domains. We can use multi-mix login - simple case to account for is Firstname[/s]Lastname logins. 

I tried several ways to escape this ... such as follows, with no success.

c:\\Users\\...
c:/Users/...
c://Users//...

I can't use the quotes in the configuration to control that command, so not sure where to look in the code (nor have the time to look / debug). Can you help? I am trying to integrate into a Mac shop here, because I do .NET work .. and eslint is a requirement to get past code review with the folks around me.

**Comment by deadem** [comment]
Hello!

There is example of config with spaces in the path:

<linter extension=".js" command="&quot;C:\Users\FirstName
SecondName\AppData\Roaming\npm\eslint.cmd&quot; --format checkstyle"/>




2018-03-20 17:36 GMT+03:00 JohnWallerStudioLabs <notifications@github.com>:
