### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by EstherMoellman** [deadem/notepad-pp-linter#10]
Hi,

Thank you for NP-PP-LINTER.

I have NP 64-bit, and it rejects LINTER's installation by saying that LINTER is 32-bits. Please, am I doing something wrong? I tried to look after LINTER 64-bit but have found nothing. Your help will be welcome.

Thanks in advance!

**Comment by deadem** [comment]
Hello!

Just added x64 version of plugin: https://github.com/deadem/notepad-pp-linter/blob/master/bin/x64/linter.dll

or you can update the whole package from sourceforge: https://sourceforge.net/projects/notepad-linter/

**Comment by EstherMoellman** [comment]
Hi @deadem !  

First, thank you!

Second, I apologize for my ignorance, I have a newbie question: Is your plugin a CSS validator for NP++? This is what I am looking for, a CSS validator/corrector etc for NP++. I have a very basic CSS' knowledge, but I like to mess with my Firefox. I use Stylus (add-on/extension) when I write CSS, and it corrects my CSS' syntax in real time. However, many times I like to exchange scripts with other FF' users, so I use "pastebin". But recently I discovered NP++ and it is very nice. I just need the NP++ CSS' corrector.

Do you have any suggestion?
Your plugin?
Other plugin?

Thank you in advance.

**Comment by deadem** [comment]
stylus have a stylint linter and a checkstyle-compatible plugin that alows use it with notepad++ linter:
https://github.com/SimenB/stylint
https://www.npmjs.com/package/@zalari/stylint-checkstyle-reporter

**Comment by EstherMoellman** [comment]
@deadem , thanks a lot for your answer.

In my previous comment I meant by "Stylus", the add-on/extension for browsers. So, I don't have the Stylus software, never saw it, and I know nothing about it. After your answer I googled the subject, and it seems that first I will need to install this Stylus software, and only then I will need to install the "stylint linter and a checkstyle-compatible plugin" you recommended me. My question is: Is there an easier way to use NP++ with a real-time CSS' syntax checker?

I am not a software programmer.
And I am a newbie at CSS.
I just use it to mess with my browser.
So, I am looking for something simple, a kind of plugin for NP++... and that's all.

If you tell me that there is no such easier way, OK, I will install Stylus, and then I will try the "stylint linter and a checkstyle-compatible plugin" you suggested me. But please don't blame me, first I need to ask you for an easier solution (a simple NP++ plugin will be fantastic).

Thank you once again!

**Comment by deadem** [comment]
If you look for an easier way, try VS Code, ATOM or Sublime Text instead of NP++. They are have embedded CSS-linters (or simple plugins) which NP++ have not and require a bunch of standalone software.
