### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by axtens** [deadem/notepad-pp-linter#12]
1. Down the bottom left of my screen it reads `Linter: Invalid output format. Only checkstyle-compatible output allowed.` Why is that there and what do I do about it?
 1. I have red line boxes around certain elements of the script. What does this mean?

**Comment by deadem** [comment]
Only checkstyle-compatible linters supported, i.e. `eslint.cmd --format checkstyle` https://eslint.org/docs/user-guide/formatters/#checkstyle

Move the cursor over the red box and error description will appear in the status line.
