### ISSUE TITLE
Request for docs : screenshot in README

### ISSUE THREAD

**Issue by Lucas-C** [deadem/notepad-pp-linter#14]
Could you please add a screenshot to the README.md showing how this plugin visually integrate in Notepad++ ?

**Comment by deadem** [comment]
Something like this?
https://sourceforge.net/projects/notepad-linter/

**Comment by Lucas-C** [comment]
Yes, perfect ! :)

**Comment by deadem** [comment]
done

**Comment by Lucas-C** [comment]
Thank you !
