### ISSUE TITLE
eslint fails to run from E drive

### ISSUE THREAD

**Issue by David-dp-** [deadem/notepad-pp-linter#16]
I followed the latest guidance about eslint https://eslint.org/docs/user-guide/command-line-interface and installed it as a local npm module. I can get it to run while my shell is Windows Subsystem for Linux (WSL2)

/mnt/e/Tools/NodeJs$ node_modules/.bin/eslint --config node_modules/.bin/.eslintrc.json <filepathToJsToCheck>

But it fails when I configure it for linter assuming a cmd shell:

<?xml version="1.0" encoding="utf-8" ?>
<NotepadPlus>
  <linter extension=".js" command="E:\Tools\NodeJs\node_modules\.bin\eslint --config 'E:\Tools\NodeJs\node_modules\.bin\.eslintrc.json' "/>
</NotepadPlus>

Can linter invoke using WSL2 as its shell?

**Comment by deadem** [comment]
There is no shell invoke. Plugin just create child process:
https://github.com/deadem/notepad-pp-linter/blob/master/file.cpp#L42
So only win-compatible commands allowed. 

Can you wrap a linter call into .bat-file?
