### ISSUE TITLE
[phpcs] Invalid output format. Only checkstyle-compatible output allowed

### ISSUE THREAD

**Issue by hnworisa** [deadem/notepad-pp-linter#19]
Hello,

Linter keeps returning the following error “Linter: Invalid output format. Only checkstyle-compatible output allowed.” even though running the command in cmd produces valid XML containing `<checkstyle version=“3.5.6”>`.

Here’s my installation info
Notepad++v7.9 (Windows 10) 64
phpcs v3.5.6

My linter configuration for php is
`<linter extension=“.php” command=“C:\xampp\php\phpcs.bat —report=checkstyle”/>`

I managed to setup eslint but phpcs has refused to work.

**Comment by deadem** [comment]
Can you attach an example of result XML?

**Comment by hnworisa** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="3.5.6">
<file name="C:\xxx\xxx\xxx\xxx\xxx\xxx.php">
 <error line="1" column="1" severity="warning" message="A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic with side effects, but should not do both. The first symbol is defined on line 4 and the first side effect is on line 2." source="PSR1.Files.SideEffects.FoundWithSymbols"/>
</file>
</checkstyle>
```

**Comment by deadem** [comment]
The output seems to be absolutely legal. So there may be an error at runtime, in environment or in the command in config file. Can you attach your config file?

**Comment by pablo-sg-pacheco** [comment]
Hello,
I have the same problem. What config file are you referring to?
