### ISSUE TITLE
Cannot find module.

### ISSUE THREAD

**Issue by Am-per-Sand** [deadem/notepad-pp-linter#21]
Notepad++ 7.8.4 (64-bit)
```
Cannot find module.

linter.dll is not compatible with the current version of Notepad++
```
Can you please provide detailed manual plugin install instructions?

**Comment by deadem** [comment]
You should get a 64-bit version of linter: https://github.com/deadem/notepad-pp-linter/blob/master/bin/x64/linter.dll

**Comment by Am-per-Sand** [comment]
This is exactly the file I have been trying to use and that have caused the error message above.

To clear it even more: I have put the 64-bit version of linter file `linter.dll`  in the `plugins` directory of the npp and selected it from the program through: `Settings` -> `Import` -> `Import plugin(s)...`

**Comment by deadem** [comment]
I've download Notepad++ 7.8.4 from there: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.bin.x64.zip

Unpack
Make subfolder in plugins: plugins/Linter
Copy linter.dll to plugins/Linter
Run notepad++.exe
![1800](https://user-images.githubusercontent.com/7988931/101934020-107fd380-3bee-11eb-81a1-0f407ae030ab.png)

**Comment by Am-per-Sand** [comment]
thank you for detailed install instructions. I followed them, but it still resulted in the same error  message.

As this has been already observed, my suggestion is to check whether `linter.dll` requires additional dependency and "advertise" it in any way, a suggested in the [notepad forum](https://community.notepad-plus-plus.org/post/53556).

In the meantime I followed your install instructions on another machine and succeeded in correctly using `linter.dll`. However I noticed the difference in MS Visual Studio libraries installed. Please compare:

Error on attempt of running `linter.dll`:
```
Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Apps\Notepad\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.630
Plugins : MarkdownViewerPlusPlus.dll 

Microsoft Visual C++ 2019 X86 Minimum Runtime - 14.26.28720
Microsoft Visual C++ 2019 X86 Additional Runtime - 14.26.28720
```

Correct running of `linter.dll`:
```
Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll linter.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll XBrackets.dll XMLTools.dll
 
Microsoft Visual C++ 2008 Redistributable - x64 9.0.21022       9.0.21022       
Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219     10.0.40219              
Microsoft Visual C++ 2015 x64 Additional Runtime - 14.0.23026   14.0.23026        
Microsoft Visual C++ 2015 x64 Minimum Runtime - 14.0.23026      14.0.23026      
Microsoft Visual C++ 2015 x86 Minimum Runtime - 14.0.23026      14.0.23026      
MSXML 4.0 SP2 Parser and SDK                                    4.20.9818.0     
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161  9.0.30729.6161  
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161  9.0.30729.6161  
Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030   11.0.61030      
Microsoft Visual C++ 2005 Redistributable (x64)                 8.0.50727.42          
Microsoft Visual C++ 2005 Redistributable                       8.0.56336       
Microsoft Visual C++ 2015 x86 Additional Runtime - 14.0.23026   14.0.23026      
Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030      11.0.61030      
 ```

**Comment by deadem** [comment]
`VS2015 Redistributable` libs is required. Older Notepad++ versions ships with it, but current builds targeted to 2019 runtime so it is required to install manually.
