### ISSUE TITLE
Not updating in real-time

### ISSUE THREAD

**Issue by camAtGitHub** [deadem/notepad-pp-linter#23]
Hello,
I have got this to work with shellcheck (BASH Linter) except it doesn't update in real-time - It only works when I either load notepad++ (and it opens a *.sh file) or I switch back to another document tab and then back to the *.sh file again.

`<?xml version="1.0" encoding="utf-8" ?>
<NotepadPlus>
  <linter extension=".sh" command="C:\Users\cam\scoop\shims\shellcheck.exe -f checkstyle"/>
</NotepadPlus>`

I have also tried in STDIN mode too, it also does not update in realtime (but it works as per above).

Any suggestions?

```Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.928
Current ANSI codepage : 1252
Plugins : AutoSave.dll Comment Wrap.dll ComparePlugin.dll Linter.dll mimeTools.dll NppConverter.dll NppEventExec.dll NppExec.dll NppExport.dll urlPlugin.dll 
```
```
Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.40660            12.0.40660       
Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.40660               12.0.40660       
Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40660            12.0.40660       
Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40660               12.0.40660       
Microsoft Visual C++ 2017 x86 Additional Runtime - 14.13.26020           14.13.26020      
Microsoft Visual C++ 2017 x86 Minimum Runtime - 14.13.26020              14.13.26020      
Microsoft Visual C++ 2019 X64 Additional Runtime - 14.28.29914           14.28.29914      
Microsoft Visual C++ 2019 X64 Minimum Runtime - 14.28.29914              14.28.29914      
```

**Comment by pandadiestro** [comment]
I have this same problem, maybe it has to do with one of the updates? (I'm currently using np++ 8.4.5 64bit)

**Comment by ThosRTanner** [comment]
I have had this start happening to me since I had to update to windows 11 recently. 

It's as though it is missing the event saying the buffer contents have changed, and is still using the old information (and getting very confused because the line/character positions are now wrong), and something to do with switching to a different file and switching back causes it to run properly.

**Comment by ThosRTanner** [comment]
This appears to be due to changes in notepad++ to support >4G files, and subsequent header changes. I'm preparing a PR
