### ISSUE TITLE
can i integrate phpmd in notepad++

### ISSUE THREAD

**Issue by StephanKrauss** [deadem/notepad-pp-linter#3]
Hello,

i have a question.
Is there a way to integrate phpmd in notepad++ ?

Your sincerly Stephan

**Comment by deadem** [comment]
Sure, but phpmd needs a checkstyle-compatible output format. If phpmd doesn't support it by default you can request for checkstyle support by [create an issue](https://github.com/phpmd/phpmd) and/or make a PR.
