### ISSUE TITLE
Linter: Invalid output, but execution from command line is working

### ISSUE THREAD

**Issue by dodmi** [deadem/notepad-pp-linter#37]
Error in NPP status bar:
![image](https://github.com/deadem/notepad-pp-linter/assets/4572946/a5436589-1853-45e9-89dd-ce1cf19e078b)

Config:
![image](https://github.com/deadem/notepad-pp-linter/assets/4572946/04c3774a-8069-4cc4-bded-cd3520f67544)

Execution from command line:
![image](https://github.com/deadem/notepad-pp-linter/assets/4572946/085b8421-8111-463b-bcda-d64710a4cae3)

Is there a possibility to see the output, when the plugin executes the command?

**Comment by jpyrat** [comment]
Same for me.

I'm using https://github.com/deadem/notepad-pp-linter/issues/27#issuecomment-1941650890 tricks

linter.tmp seems good : 
```
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="3.9.0">
<file name="C:\laragon\_spipmu4_\plugins\soyezcreateurs\inc\sc_agenda.php">
 <error line="1741" column="18" severity="error" message="Expected at least 1 space before &quot;=&quot;; 0 found" source="PSR12.Operators.OperatorSpacing.NoSpaceBefore"/>
 <error line="1741" column="18" severity="error" message="Expected at least 1 space after &quot;=&quot;; 0 found" source="PSR12.Operators.OperatorSpacing.NoSpaceAfter"/>
</file>
</checkstyle>
```
