### ISSUE TITLE
Space in path seems to result in error 'Invalid output format'

### ISSUE THREAD

**Issue by poberlohr** [deadem/notepad-pp-linter#4]
Hi,

I just tried to get this plugin working using ESLint, but I got an error when I opened my file index.js:

> Linter: Invalid output format. Only checkstyle-compatible output allowed.

After trying this and that for way too long I moved my project folder to 

    E:\c-d\

instead of

    E:\Eigene Dateien\c-d\

and it worked, so I think the space in `Eigene Dateien` lets the linter fail.

**Comment by deadem** [comment]
You need to quote the path:

`
<linter extension=".js" command="&quot;E:\Path with spaces\jscs.cmd&quot; --reporter=checkstyle"/>
`

**Comment by poberlohr** [comment]
There are no spaces in my path to *.cmd.

The spaces are in the path to the file the linter should check.
So in the XML that ESLint returns there are spaces in the path.

I'll post the XML that ESLint creates after the weekend, if that helps

**Comment by deadem** [comment]
Ow! Thanks! You can download the updated version from sourceforge: https://sourceforge.net/projects/notepad-linter/

**Comment by poberlohr** [comment]
Great, it works now, thanks!

**Comment by raja-muhammad-asher** [comment]
I am receiving the following error in Windows 10 64 Bit. Although there is no space in the paths to the cmd file and my JS file.

> Linter: Invalid output format. Only checkstyle-compatible output allowed.

**Comment by deadem** [comment]
> I am receiving the following error in Windows 10 64 Bit. Although there is no space in the paths to the cmd file and my JS file.
> 
> > Linter: Invalid output format. Only checkstyle-compatible output allowed.

You should check the linter ouput, try to type and run command from the command line.

**Comment by raja-muhammad-asher** [comment]
Command line is working perfectly. I have local install of eslint for my project. The path to cmd is D:\node\nodetest2\node_modules\.bin\eslint.cmd

**Comment by bunglegrind** [comment]
> Command line is working perfectly. I have local install of eslint for my project. The path to cmd is D:\node\nodetest2\node_modules.bin\eslint.cmd

I have the same issue. No spaces in both  the command path and the file path, but linter gives me the same error message.

This is my configuration file:

`<?xml version="1.0" encoding="utf-8" ?>
<NotepadPlus>
  <linter extension=".js" command="&quot;C:\Users\xxx\AppData\Roaming\npm\eslint.cmd&quot; --format=checkstyle"/>
</NotepadPlus>`

My environment:

**Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : JSMinNPP.dll Linter.dll mimeTools.dll NppConverter.dll** 

Any suggestions?

Thanks

**Comment by medeaoblongata** [comment]
Same issue here. No spaces in command path or file path

**Comment by Owyn** [comment]
Same issue here.

Could it be due to notepad++ using other-direction slashes for some of the target path `/` `\` perhaps ?

**Comment by pablo-sg-pacheco** [comment]
I also have the same problem. The command line is working just fine
