### ISSUE TITLE
Not real-time

### ISSUE THREAD

**Issue by gweinfurther** [deadem/notepad-pp-linter#40]
If I get an error flagged in my JS file, then correct it, the marker and error message remains. How do I get linter to recheck the file?

**Comment by mike406** [comment]
Having this issue as well. Sometimes it will update but it is very delayed. I'm confused if it only re-processes when the file is saved but that doesn't seem to be the case either.

**Comment by andrija-naglic** [comment]
I would love to see an option in the plugin settings to select how often in should re-process.
Sometimes I'd like it to be on save only.
Sometimes I'd also like to turn this off.

Currently, it's hard to actually code - if I type too fast and the check happens, for a brief moment the Notepad window loses focus and some of my typed characters are lost.

**Comment by deadem** [comment]
Can't fix without the exact steps to reproduce.
