### ISSUE TITLE
Linter doesn't seem to be using stdin

### ISSUE THREAD

**Issue by mike3085** [deadem/notepad-pp-linter#41]
Using flake8 with python, which supports reading in a .py file from stdin. The linter plugin for some reason is still generating the tmp file despite me enabling `stdin="1"`. Anything I am doing wrong?

![image](https://github.com/deadem/notepad-pp-linter/assets/3455235/4605dcfc-4436-4451-bea2-f3d90c9b6c62)

```
<?xml version="1.0" encoding="utf-8" ?>
<NotepadPlus>
  <linter stdin="1" extension=".py" command="flake8 --format=checkstyle"/>
</NotepadPlus>
```

**Comment by mike406** [comment]
Nevermind, I was using the version from Plugin Manager which seems to be a release prior to when this was implemented. Any way you can update your version in Plugin Admin, I'm sure others would appreciate it.

**Comment by mike406** [comment]
Upon further inspection, stdin is still not working for me. I'm not getting anything highlighted in my file. If I remove stdin="1" then it is working. flake8 supports giving it a file via stdin so I am not sure why this is not working right.

**Comment by mike406** [comment]
Resolved
