### ISSUE TITLE
Question: How to add css, html and python lintering

### ISSUE THREAD

**Issue by merlinuwe** [deadem/notepad-pp-linter#43]
Thanks for your great plugin.

How can I add css, html and python lintering? I need some documentation, because I'm new in this.

**Comment by deadem** [comment]
You should refer to the documentation of your linter to consult about how to enable the checkstyle-compatible output.
Then add the config line:
```
<linter extension=".py" command="path_to_your_python_linter --command_line_parameters"/>
```

Similarly, for CSS and HTML:
```
<linter extension=".css" command="path_to_your_css_linter --command_line_parameters"/>
<linter extension=".html" command="path_to_your_html_linter --command_line_parameters"/>
```
