### ISSUE TITLE
Identify error?

### ISSUE THREAD

**Issue by BoatrightTBC** [deadem/notepad-pp-linter#5]
The real-time linting is extremely cool.  But is there some way to identify WHAT the error is?  It's not always obvious, even with my carefully tuned .eslintrc.json

**Comment by deadem** [comment]
Move cursor to the red box and error message will appear in the left bottom corner of notepad++

![2016-04-24 09 31 53](https://user-images.githubusercontent.com/7988931/44114167-14a56098-a013-11e8-8ed5-ddb46e3957eb.png)
