### ISSUE TITLE
How do I change the highlight to something more visible than underline?

### ISSUE THREAD

**Issue by ghost** [deadem/notepad-pp-linter#6]
Thanks for this great plugin - I'm using eslint v5.4.0 and npp-linter version dated 5th August 2018.

It puts a small, very thin red square around any errors, which is hard for someone who is colourblind.

I've had a really good look through all the NPP++ style configurator options and I can't change how to find this! I'd much rather set this to a bright yellow background, or blue and white text. Something that jumps out. Right now, it's a case of slowly scrolling and keeping a careful look-out.

Many thanks in advance.

**Comment by deadem** [comment]
There is no way to customize font color so you can change only background (hex rgb value) and alpha in range of 0-255.

Something like this:

```xml
<NotepadPlus>
  <style color="0000FF" alpha="100" />
...
```

The updated version you can get from SF: https://sourceforge.net/projects/notepad-linter/

**Comment by ghost** [comment]
Hey, that's great - super quick response, very impressed!

Just one thing though, the RGB seems to be BGR:
0000FF =red
00FF00 = green
FF0000 = blue

So yellow is now 00FFFF rather than FFFF00. This works well for me to highlight:

 `<style color="00FFFF" alpha="200" />`

Just one thing I noticed, with previous versions as well: sometimes, the error highlighted is just a small underline, rather than a complete box. Closing and reloading notepad usually fixes this.

**Comment by deadem** [comment]
Thanks! There are fix for scintilla's color reverse order, fix for check color attribute and fix for losing highlight styles.

Please update.

**Comment by ghost** [comment]
Hey, that's great - I can confirm it works! I have one more suggestion to make, will add separately!
