### ISSUE TITLE
Please add this to the official Notepad++ Plugin Repository

### ISSUE THREAD

**Issue by ghost** [deadem/notepad-pp-linter#7]
Unfortunately, all the other js linting plugins have had development abandoned, and it took me a while to discover yours because it is not in the plugin registry:
http://docs.notepad-plus-plus.org/index.php?title=Plugin_Central

I don't know if you have to get in touch with this guy, too? https://github.com/bruderstein/nppPluginManager

**Comment by deadem** [comment]
http://docs.notepad-plus-plus.org seems to be dead: http://docs.notepad-plus-plus.org/index.php?title=Plugin_Central&action=history

**Comment by deadem** [comment]
https://github.com/notepad-plus-plus/nppPluginList/pull/54
