### ISSUE TITLE
Add list of errors to a dialog window

### ISSUE THREAD

**Issue by ghost** [deadem/notepad-pp-linter#8]
There used to be an old plugin which is no longer maintained, called https://sourceforge.net/projects/jslintnpp/

A nice feature was that it provided a window at the bottom of the Notepad++ editing screen to list all the errors found. You could then just click a line and it would jump straight to the error in the code.

Would you consider implementing this feature in your plugin? Thank you!

**Comment by chcg** [comment]
Source therefore is available as svn repo here https://sourceforge.net/p/jslintnpp/code/HEAD/tree/trunk/src/ also last release 0.8.3 seems missing.

**Comment by Owyn** [comment]
or at least a hotkey to navigate to next+prev error, cuz now it's really really hard to even notice errors

**Comment by deadem** [comment]
@Owyn you can make the colors more contrast for now: https://github.com/deadem/notepad-pp-linter/issues/6#issuecomment-415482687
