### ISSUE TITLE
I cant see the error in the status bar

### ISSUE THREAD

**Issue by ThosRTanner** [deadem/notepad-pp-linter#9]
I imagine I must be doing something stupid, but. I get all the little red boxes I'd expect, but I cannot make the associated message appear in the status line at the bottom.

This is a great addon and thank you

**Comment by deadem** [comment]
Hello! Try to move blinking cursor by mouse or keyboard next to red square.

пт, 18 янв. 2019 г., 23:57 ThosRTanner notifications@github.com:

**Comment by ThosRTanner** [comment]
Oh. found it. I have an 80 column view and the message was disappearing entirely at there wasn't room for it. Will see if I can configure the menu bar.  Closing this, but #8 would be useful.
